
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://claroscuro.com.co/wp-content/uploads/config
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000
